travis:
  secure:
    BINSTAR_TOKEN: qdCngQ1YRB2NGxxRSig0fDaD57E6sZdYbshwJwUiNOySmoONx8Pn6QrNDCksR2lFVH2ULV3ZG/4nlTFF0OghU5nGu5G8vxybAbPsGVSjwH1RyCGWuUgmXj4EHNuqxGbCs47Pa+fACDe20GUJM8LMGDzDpwcPqm74bXQ5ei9bE/6pVaQtmRE5Nz0hMzu/bDdTYtXOqPmLI+N27QdJdlKiGDLnIBleDp4vssL/2gwdMdy30LpT3FijZ7cVrCQkbbkfLJsR1CvUZSngbb+puz7TPERib3a/bb3Z/HrJRqlE+XI17YGOfyDePBMqKqzTPMdEG6VRdN95svtZi/vFoGa2DBBw9qyyAtA65j5xpcIZodLDOiwHi6qtcTRTMb8GYW4jfpSV7nWdaR9RfJhbxMHqkYjUbqBgm2JnuHanx5AlWYokVdE2pY5aJHoJil/9d+FNd2Q3g7QESCHpzi36hRCExQezdfdd3l3+6JZ1XEJos0MryTFkxIFUCZOMhp1pFt4UJe+FBUoBE8DyhXMC4rsirGjptVfBwBac8tYjFVd032F1QPfHSMfprL52G+BPKLmOfcjICRaF+BX/Fp8zuIgUd9U6YkzlCGjcf6urZaBwla7wiejdvr3Fjj0N393tB7ZvlbrCpOrmnOA1S/ZwdLn59UHfTQ8BogTi8Hc58aELjtI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
